name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: zhyclouds
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_order: base.header, isocalendar
          config_timezone: Asia/Shanghai
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_from: 200
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_lines: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          repositories_affiliations: owner,collaborator
